version: '3.8'

services:

  redis:
    image: redis:latest
    container_name: spring-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Nguyen@12345"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init:/init
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools18/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "Nguyen@12345",
          "-C",
          "-Q",
          "SELECT 1"
        ]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 40s
    restart: unless-stopped

volumes:
  sqlserver_data:
  redis_data:
